# Generated by Django 6.0.4 on 2026-04-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_overdue',
        ),
    ]
