# Generated by Django 6.0.4 on 2026-04-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_priority_task_created_at_task_is_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_overdue',
        ),
    ]
